server:
  port: ${PORT:9101}

spring:
  application:
    name: order-service  
  rabbitmq:
    host: 47.104.216.134
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
        
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka
      
feign:
  hystrix:
    enabled: true

test:
  number: 8888
  

