server:
  port: 8005

spring:
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka
feign:
  hystrix:
    enabled: true

test:
  number: 3000
